### PR TITLE
Production values also updated with endpointUrl

### PR DESCRIPTION
**Pull request by appunni-dishq**

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/Percona-Lab/percona-helm-charts?pullRequest=23) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/Percona-Lab/percona-helm-charts?pullRequest=23) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/Percona-Lab/percona-helm-charts?pullRequest=23) it.</sub>

**Comment by tplavcic** [comment]
Thank you for the update!

**Comment by tplavcic** [comment]
@appunni-dishq Please next time increase the charts version so that the tests can run (they are failing like this: `pxc-db => (version: "0.1.9", path: "charts/pxc-db") > Chart version not ok. Needs a version bump!`).Since we need to create the update for PXC

**Comment by appunni-m** [comment]
Why do we need to update chart version for documentation updation ?

**Comment by tplavcic** [comment]
You're correct about this PR, but for example you had a fix for PMM enabling logic and there it wasn't just documentation so I guess I was commenting on the wrong PR.
Thank you for your fixes!

**Pull request merged**
