### PR TITLE
PMM not found (bug) while installing proxysql

### PR DESCRIPTION
**Pull request by appunni-dishq**

### CODE REVIEW

**Comment by tplavcic** [comment]
Thank you for the update!

**Comment by appunni-m** [comment]
I don't think PMM is working , I think it is a bug. After enabling PMM it stopped working for me even after doing this. Who ever disabled it did it to disable PMM

**Comment by tplavcic** [comment]
Hi, your fix seems to be fine, if PMM is not working then it's another problem and needs to be solved on another level. Enabling PMM here only enables PMM agents, so PMM needs to be installed and setup before enabling here.

**Comment by appunni-m** [comment]
Okay seems fair. I will bump version next time. Thanks

**Pull request merged**
